---
- hosts: all
  pre_tasks:
    - name: Install docker
      include_role:
        name: docker
    - name: Create a network
      community.docker.docker_network:
        name: '{{ network_name }}'
  roles:
    - role: db
    - role: wordpress
    - role: phpmyadmin
