---
- hosts: all
  pre_tasks:
    - name: Install docker
      include_role:
        name: docker
    - name: Create a network
      community.docker.docker_network:
        name: '{{ network_name }}'
    - name: Create wordpress volume
      community.docker.docker_volume:
        name: 'wordpress'
    - name: Create phpmyadmin volume
      community.docker.docker_volume:
        name: 'phpmyadmin'
  roles:
    - db
    - wordpress
    - phpmyadmin
    - nginx
