---
- hosts: all
  tasks:

    - name: Create Network
      community.docker.docker_network:
        name: wordpress

    - name: Deploy Wordpress
      community.docker.docker_container:
        name: wordpress
        image: wordpress:latest
        ports:
          - "80:80"
        networks:
          - name: wordpress
        volumes:
          - wordpress:/var/www/html
        env:
          WORDPRESS_DB_HOST: "db"
          WORDPRESS_DB_USER: "{{ lookup('env','MYSQL_USER') }}"
          WORDPRESS_DB_PASSWORD: "{{ lookup('env','MYSQL_PASSWORD') }}"
          WORDPRESS_DB_NAME: "{{ lookup('env','MYSQL_DATABASE') }}"
        restart_policy: always

    - name: Deploy MYSQL
      community.docker.docker_container:
        name: db
        image: mysql:5.7
        networks:
          - name: wordpress
        volumes:
          - db:/var/lib/mysql
        env:
          MYSQL_USER: "{{ lookup('env','MYSQL_USER') }}"
          MYSQL_PASSWORD: "{{ lookup('env','MYSQL_PASSWORD') }}"
          MYSQL_DATABASE: "{{ lookup('env','MYSQL_DATABASE') }}"
          MYSQL_RANDOM_ROOT_PASSWORD: '1'
        restart_policy: always

    - name: Deploy Phpmyadmin
      community.docker.docker_container:
        name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        networks:
          - name: wordpress
        ports:
          - "8080:80"
        volumes:
          - phpmyadmin:/var/www/
        env:
          PMA_HOST: "{{ lookup('env','MYSQL_DATABASE') }}"
          PMA_PORT: "3306"
          PMA_ARBITRARY: '1'
        restart_policy: always
