---
# - name: Remove image
#   community.docker.docker_image:
#     name: ggjulio/wordpress
#     state: absent
#   delegate_to: localhost
- name: Build, tag, push to dockerhub
  community.docker.docker_image:
    source: build
    build:
      path: ./images/wordpress
    name: ggjulio/wordpress
    tag: latest
    repository: ggjulio/wordpress
    push: yes
    state: present
  delegate_to: localhost


- name: Deploy Wordpress
  community.docker.docker_container:
    name: wordpress
    image: ggjulio/wordpress
    networks:
      - name: '{{ network_name }}'
    volumes:
      - wordpress:/var/www/html
    env:
      MYSQL_DATABASE: '{{ MYSQL_DATABASE }}'
      MYSQL_USER: '{{ MYSQL_USER }}'
      MYSQL_PASSWORD: '{{ MYSQL_PASSWORD }}'
      MYSQL_HOST: db      
    restart_policy: always
    state: started


# - name: Deploy Wordpress
#   community.docker.docker_container:
#     name: wordpress
#     image: wordpress:latest
#     ports:
#       - "80:80"
#     networks:
#       - name: '{{ network_name }}'
#     volumes:
#       - wordpress:/var/www/html
#     env:
#       WORDPRESS_DB_HOST: "db"
#       WORDPRESS_DB_USER: '{{ MYSQL_USER }}'
#       WORDPRESS_DB_PASSWORD: '{{ MYSQL_PASSWORD }}'
#       WORDPRESS_DB_NAME: '{{ MYSQL_DATABASE }}'
#     restart_policy: always
#     state: started
