---
- name: Deploy Phpmyadmin
  community.docker.docker_container:
    name: phpmyadmin
    image: ggjulio/phpmyadmin
    pull: yes
    networks:
      - name: '{{ network_name }}'
    volumes:
      - /phpmyadmin:/var/www/app
    restart_policy: always
    state: started
