---
- name: Deploy MYSQL
  community.docker.docker_container:
    name: db
    image: mysql:5.7
    networks:
      - name: '{{ network_name }}'
    volumes:
      - db:/var/lib/mysql
    env:
      MYSQL_DATABASE: '{{ MYSQL_DATABASE }}'
      MYSQL_USER: '{{ MYSQL_USER }}'
      MYSQL_PASSWORD: '{{ MYSQL_PASSWORD }}'
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    restart_policy: always
