---
- name: Deploy MYSQL
  community.docker.docker_container:
    name: db
    image: ggjulio/mariadb
    pull: yes
    networks:
      - name: '{{ network_name }}'
    volumes:
      - db:/var/lib/mysql
    env:
      MYSQL_GROOT_HOST: '%' # to change maybe
      MYSQL_GROOT_PASSWORD: '{{ MYSQL_ROOT_PASSWORD }}'
      MYSQL_DATABASE: '{{ MYSQL_DATABASE }}'
      MYSQL_USER: '{{ MYSQL_USER }}'
      MYSQL_PASSWORD: '{{ MYSQL_PASSWORD }}'
    restart_policy: always
    state: started
